
###
POST http://localhost:4004/odata/v4/MyServiceMain/insertDataIntoDb
Content-Type: application/json

{
  "data": {
    "idCheck":"124",
    "checkName": true,
    "checkStatus": "Passed",
    "checkBY": "Danish"
  }
}
###
GET http://localhost:4004/odata/v4/MyServiceMain/$metadata
###
GET http://localhost:4004/odata/v4/MyServiceMain/CUST
###
POST http://localhost:4004/odata/v4/MyServiceMain/CUST
Content-Type: application/json

{
  "CUSTOMER_NAME": "tata",
  "CURRENCY": "INR",
  "COUNTRY": "NEPAL"
}
### '003'	'T003'	'2'
PUT http://localhost:4004/odata/v4/MyServiceMain/CUST(8e0b26ee-2c6c-45ca-b402-fc5214dbe592)
Content-Type: application/json

{
  
  "CUSTOMER_NAME": "dan1chck",
  "CURRENCY": "inr",
  "COUNTRY": "india"
}

###
POST http://localhost:4004/odata/v4/MyServiceMain/SO
Content-Type: application/json

{
  
  "salesOrderId": "SO9001",
  "salesOrderValue": "9999",
  "date": "2025-07-11",
  "customersUUID": "ea16ab99-efed-4b7a-962e-c3182ed08f27"  
}
###
POST http://localhost:4004/odata/v4/error-mangement/createErrorRecord
Content-Type: application/json

  {
    "data": {
      "source":"TMS-GSAP",
      "interface":"Contract",
      "errorCode":"3",
      "iFlowName":"i01",
      "httpErrorCode":"32",
      "enabledForReprocessing":"Y",
      "fields":[
        {"keys":"ID","value":"008"},
        {"keys":"terminalNo","value":"T005"},
        {"keys":"folioMo","value":"3"},
        {"keys":"invNo","value":"In03"},
        {"keys":"rejectInd","value":"X"}

      ]
    }
  }

###
POST http://localhost:4004/odata/v4/error-mangement/createErrorRecord
Content-Type: application/json

  {
    "data": {
      "source":"Endure",
      "interface":"Nomination",
      "errorCode":"1",
      "iFlowName":"i01",
      "httpErrorCode":"32",
      "enabledForReprocessing":"Y",
      "fields":[
        {"keys":"ID","value":"002"},
        {"keys":"nominationKey","value":"002"},
        {"keys":"nominationItem","value":"002"},
        {"keys":"scheduleDate","value":"2025-08-30T11:59:00Z"}

      ]
    }
  }
### 		(ID='003',folioMo='T003',terminalNo='2')
GET http://localhost:4004/odata/v4/error-mangement/ContractErrors(ID='002',terminalNo='T001',folioMo='1')


### 		(ID='003',folioMo='T003',terminalNo='2')
POST http://localhost:4004/odata/v4/error-mangement/ContractErrors(ID='002',terminalNo='T001',folioMo='1')/ErrorMangement.changeRejInd
Content-Type: application/json

{
  "newValue": "g"
}
